language: php
sudo: required
php:
 - '7.2'
 - '7.3'

services:
 - mysql

before_script:
 - composer self-update
 # - chmod ugo+x bin/travis.sh
 # - ./bin/travis.sh $(phpenv version-name) $(pwd)

install:
 - travis_retry composer install --no-interaction --prefer-source

notifications:
 on_success: always
 on_failure: always
